#!/usr/bin/env bash

setup_remote () {
    name=$1
    url=$2

    echo ""
    echo "setup remote \"$name\" -> $url"
    git remote rm $name 2> /dev/null
    git remote add $name $url
    git fetch $name
}

setup_remote "production" "zope@eta.4teamwork.ch:/home/zope/eta.4teamwork.ch/35-plone-fontanabau.ch"
